# Generated by Django 5.2.1 on 2025-05-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0005_transaction_selling_price_per_liter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltype',
            name='selling_price_per_liter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
