# Generated by Django 5.2.1 on 2025-05-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0006_fueltype_selling_price_per_liter'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='selling_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
